### ISSUE TITLE
Custom Theme Support

### ISSUE THREAD

**Issue by hyperrealgopher** [hyperrealgopher/waffle#10]
Make it so you can:

  * Toggle emoji mode
  * Change arrow/"asterisk" to other characters
  * Change borders
  * Change all the colors and styles

I believe this is pretty much all mostly doable through the Brick INI thingy.

**Comment by hyperreal-gopher** [comment]
Store `~/.config/waffle/theme.ini`: especially need a feature for setting background to "transparent."

Test colors here so BG reset looks good here: gopher://zaibatsu.circumlunar.space:70/1/~shufei

**Comment by hyperreal-gopher** [comment]
I believe `brick` has a lot of support for `ini` theming?

**Comment by hyperreal-gopher** [comment]
Have "transparent" background as a setting.

**Comment by hyperreal-gopher** [comment]
Merely tangentially related: #14

**Comment by hyperreal-gopher** [comment]
Needs to have TUI for editing the above INI, like with open.ini

**Comment by hyperrealgopher** [comment]
https://hackage.haskell.org/package/brick-0.55/docs/Brick-Themes.html

**Comment by hyperrealgopher** [comment]
implemented in v0.19.0
