### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by hyperrealgopher** [hyperrealgopher/waffle#44]
- [ ] Snap
- [ ] Maybe standalone (static) Linux

**Comment by hyperreal-gopher** [comment]
Tip for standalone linux:

https://hackage.haskell.org/package/file-embed-0.0.10.1/docs/Data-FileEmbed.html

note of linux version and other stuff like that. maybe break these different release targets (snap, openbsd, etc.) into separate issues.

**Comment by hyperreal-gopher** [comment]
Previous attempt resulted in many crashes. Maybe look into AppImage.
